- name: Set GLB DC REST API endpoint for {{ data_center.name }}
  ansible.builtin.set_fact:
    fad_api_endpoint_glb_dc: https://{{ ansible_host }}/api/global_load_balance_data_center?vdom={{ fad_vdom }}&mkey={{ data_center.name }}
  tags:
    - fad_glb_dc

- name: Print out the GLB DC REST API endpoint for {{ data_center.name }}
  ansible.builtin.debug:
    msg: "This FAD GLB DC REST API endpoint: {{ fad_api_endpoint_glb_dc }}"
  tags:
    - fad_glb_dc
    - debug

# - name: Get the existing value of the data center entry for {{ data_center.name }}
#   ansible.builtin.uri:
#     method: GET
#     url: "{{ fad_api_endpoint_glb_dc }}"
#     body_format: "{{ fad_api_uri_params.body_format }}"
#     validate_certs: "{{ fad_api_uri_params.validate_certs }}"
#     return_content: "{{ fad_api_uri_params.return_content }}"
#     status_code: "{{ fad_api_uri_params.status_code }}"
#     headers: "{{ fad_api_header }}"
#   register: fad_glb_dc_existing_data
#   delegate_to: localhost
#   tags:
#     - fad_glb_dc

- name: Get the existing value of the data center entry for {{ data_center.name }}
  ansible.builtin.include_tasks: fad_rest_api.yaml
  vars:
    http_method: 'GET'
  tags:
    - fad_glb_dc
  
- name: Print the existing value of data center entry for {{ data_center.name }}
  ansible.builtin.debug:
    var: fad_glb_dc_existing_data.json.payload
  delegate_to: localhost
  tags:
    - fad_glb_dc
    - debug

- name: Write DNS Policy request body template for {{ data_center.name }}
  ansible.builtin.set_fact:
    request_body: |
      {
        "mkey": "{{ data_center.name }}",
        "location": "{{ data_center.location }}"
      }
  tags:
    - fad_glb_dc

- name: Print out the request_body result for {{ data_center.name }}
  ansible.builtin.debug:
    var: request_body
  tags:
    - fad_glb_dc
    - debug

- name: Create new data center entry if entry not found for {{ data_center.name }}
  ansible.builtin.uri:
    method: POST
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ request_body }}"
  register: fad_glb_dc_post_result
  delegate_to: localhost
  when: fad_glb_dc_existing_data.json.payload.mkey is undefined
  changed_when: "fad_glb_dc_post_result.json.payload == 0"
  failed_when: "fad_glb_dc_post_result.json.payload != -15 and fad_glb_dc_post_result.json.payload != 0"
  tags:
    - fad_glb_dc

- name: Update the data center entry if entry exist for {{ data_center.name }}
  ansible.builtin.uri:
    method: PUT
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ request_body }}"
  register: fad_glb_dc_put_result
  delegate_to: localhost
  when: >
    (fad_glb_dc_existing_data.json.payload.mkey is defined) and
    (data_center.location != fad_glb_dc_existing_data.json.payload.location)
  failed_when: "fad_glb_dc_put_result.json.payload != -15 and fad_glb_dc_put_result.json.payload != 0"
  tags:
    - fad_glb_dc

- name: Check if the data center value has changed for {{ data_center.name }}
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_dc_new_data
  changed_when: "fad_glb_dc_new_data.json.payload != fad_glb_dc_existing_data.json.payload"
  delegate_to: localhost
  tags:
    - fad_glb_dc

- name: Print the new value of data center entry for {{ data_center.name }}
  ansible.builtin.debug:
    var: fad_glb_dc_new_data.json.payload
  delegate_to: localhost
  tags:
    - fad_glb_dc
    - debug
