- name: Get the existing value ofnano data center entry for {{ data_center.name }}
  ansible.builtin.uri:
    method: "{{ http_method }}"
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_glb_dc_existing_data
  delegate_to: localhost
  when: http_method == 'GET'
  tags:
    - fad_glb_dc

- name: Get the existing value ofnano data center entry for {{ data_center.name }}
  ansible.builtin.uri:
    method: "{{ http_method }}"
    url: "{{ fad_api_endpoint_glb_dc }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
    body: "{{ request_body }}"
  register: fad_glb_dc_existing_data
  delegate_to: localhost
  when: (http_method == 'POST') or (http_method == 'PUT')
  tags:
    - fad_glb_dc