---

- name: Create/update GLB Data Center entries.
  tags: [fad_glb_data_center]
  vars:
    fad_glb_data_center_api_endpoint: "{{ fad_base_url + fad_endpoint.glb_data_center }}"
  ansible.builtin.import_tasks: fad_glb_data_center.yaml
