---
# ./.github/workflows/release.yaml

name: Release

on:
  push:
    branches:
      - main

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4
      - name: Create a release.
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: v1.1.3
  push-to-galaxy:
    runs-on: ubuntu-latest
    needs: github-release
    if: ${{ needs.github-release.result == 'success' }}
    steps:
      - name: Checkout repo.
        uses: actions/checkout@v4
      - name: Set up Python 3.
        uses: actions/setup-python@v5
      - name: Install Ansible.
        run: pip3 install ansible-core
      - name: Import role to Galaxy.
        run: >-
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
